/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpWindowUI.java
 *
 * Created on 10.05.2011, 15:26:07
 */
package de.blankedv.sx3pc;

import java.awt.Desktop;
import java.net.URI;
import java.util.prefs.Preferences;

import static de.blankedv.sx3pc.InterfaceUI.VERSION;

/**
 *
 * @author mblank
 */
public class HelpWindowUI extends javax.swing.JFrame {

    Desktop desktop = Desktop.getDesktop();
    Preferences prefs = Preferences.userNodeForPackage(this.getClass());

    static final String germanURI = "http://www.oscale.net/sx3";
    static final String englishURI = "http://www.oscale.net/en/sx3";
    static final String githubURI = "https://github.com/michael71/SX3-PC";

    /** Creates new form HelpWindowUI */
    public HelpWindowUI() {
        initComponents();
        if (prefs.get("locale", "Deutsch").contains("Deu")) {
            jLabel1.setText("<html><p>OpenSource Programm SX3-PC von Michael Blank</p>"+
                    "<p>Version "+VERSION+"</p><br>"+
                    "<p>hier Links zu Code und Dokumentation:</p></html>");

            lblCodelink.setText("<html><a href='"+githubURI+"'>" +
                    "github/michael71/SX3-PC</a></html>");
            
            lblDoculink.setText("<html><a href='"+germanURI+"'> "+
                    "SX Monitor Beschreibung auf oscale.net</a></html>");
        } else {
            jLabel1.setText("<html><p>OpenSource Program SX3-PC by Michael Blank</p>"+
                    "<p>Version "+VERSION+"</p>"+
                    "<p>for more info see:</p>");
            lblCodelink.setText("<html><a href='"+githubURI+"'> "+
                    "github/michael71/SX3-PC</a></html>");
            lblDoculink.setText("<html><a href='"+englishURI+"'> "+
                    "SX monitor description on web</a></html>");
        }

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDoculink = new javax.swing.JLabel();
        lblCodelink = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("jLabel1");

        lblDoculink.setText("lblDoculink");
        lblDoculink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoculinkMouseClicked(evt);
            }
        });

        lblCodelink.setText("lblCodelink");
        lblCodelink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCodelinkMouseClicked(evt);
            }
        });

        jLabel4.setText("Code:");

        jLabel5.setText("Docu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(20, 20, 20)
                                .addComponent(lblDoculink, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblCodelink, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCodelink, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoculink, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDoculinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoculinkMouseClicked
        try {
            if (prefs.get("locale", "Deutsch").contains("Deu")) {
                desktop.browse(new URI(germanURI));
            } else {
                desktop.browse(new URI(englishURI));
            }
        } catch (Exception e) {
            System.out.println("could not open browser");
        }
    }//GEN-LAST:event_lblDoculinkMouseClicked

    private void lblCodelinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCodelinkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodelinkMouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCodelink;
    private javax.swing.JLabel lblDoculink;
    // End of variables declaration//GEN-END:variables
}
