package de.blankedv.sx3pc;

import java.io.IOException;
import java.io.File;
import java.io.FileWriter;
import java.util.prefs.Preferences;

import static de.blankedv.sx3pc.InterfaceUI.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VtestUI.java
 *
 * Created on 19.02.2012, 08:54:23
 */


/**
 *
 * @author mblank
 */
public class VtestUI extends javax.swing.JFrame {
    private static final long serialVersionUID = 5313123456412L;
    private int sensorAdr;
    private int locoAdr;
    private Preferences prefs;
    Byte[] b = {(byte) (127 + 128), 0 };
    private static final double streckenlaenge = 1 * Math.PI * 43.75;   // cm  = halbe runde
    private static int count = 0;
    long startTime;
    long elapsedTime;
    int speed;
    

    File outputFile = new File("vkennlinie.txt");
    FileWriter out ;
    /** Creates new form VtestUI */

    public VtestUI() {
        initComponents();
        this.setVisible(true);
        prefs = Preferences.userNodeForPackage(this.getClass());
        loadPrefs();
    }

    public void sensorFeedback(int d) {
        d = d & 192;  // bit 7 and 8
        // measure from d==64 to again d==128  (= half Round)
        if ((d == 128) || (d == 64))  {
            if (count == 0) {
                startTime = System.currentTimeMillis();
            } else  {
                elapsedTime = System.currentTimeMillis() - startTime;
                startTime = System.currentTimeMillis();
                lblCount.setText(String.valueOf(elapsedTime)+" [ms]");
                double v1 = (streckenlaenge*1000.0)/(elapsedTime);
                System.out.println("V-Stufe= "+speed + " t="+elapsedTime+" [ms] - V= "+v1+"[cm/sec]");
                try { out.write(speed+";"+elapsedTime/(1000.0)+";"+v1+"\n"); } catch (IOException e) {};
            }
            count++;
            if (count == 3)  {   // nächste V-Stufe
                count = 0;
               speed = speed + 3;
               if (speed > 31)  {  // stop
                   speed = 0;
                   try { out.close(); } catch  (IOException e) {};
               }
               sxi.sendLoco(locoAdr, speed, false, true, false) ;
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddress = new javax.swing.JLabel();
        comboSelAddress = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        comboSelAddressLoco = new javax.swing.JComboBox();
        lblCount = new javax.swing.JLabel();

        setTitle("V-Test");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblAddress.setText("Adr");

        comboSelAddress.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111" }));
        comboSelAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelAddressActionPerformed(evt);
            }
        });

        jLabel1.setText("Adr Besetztmelder (Kanäle = 7 und 8)");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jLabel2.setText("Adr Lok");

        lblAddress1.setText("Adr");

        comboSelAddressLoco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111" }));
        comboSelAddressLoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelAddressLocoActionPerformed(evt);
            }
        });

        lblCount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAddress1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSelAddressLoco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCount)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSelAddressLoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress1)))
                    .addComponent(lblCount))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStop)
                    .addComponent(btnStart))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSelAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelAddressActionPerformed
        sensorAdr = comboSelAddress.getSelectedIndex()+1;
        sxi.registerFeedback(sensorAdr);
}//GEN-LAST:event_comboSelAddressActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        count = 0;   // neuer Start der messung
        //Gleisspannung Ein 
        sxi.switchPowerOn();
        sleepSomeMillis();
        speed = 3;
        sxi.sendLoco(locoAdr, speed, false, true, false) ;
        try {
             outputFile = new File("vkennlinie.txt");
             out = new FileWriter(outputFile);
        } catch  (IOException e) {}; 
   
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        speed = 0;
        sxi.sendLoco(locoAdr, speed, false, true, false) ;
        try { out.close(); } catch  (Exception e) {};  // IOException or NullPointerException 
    }//GEN-LAST:event_btnStopActionPerformed

    private void comboSelAddressLocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelAddressLocoActionPerformed
        locoAdr =  comboSelAddressLoco.getSelectedIndex()+1;
    }//GEN-LAST:event_comboSelAddressLocoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sxi.unregisterFeedback();
        savePrefs();
        vtest = null;  // to enable opening a VtestUI window again in Interface UI
    }//GEN-LAST:event_formWindowClosing


    private void savePrefs() {
        // fuer SX3 Programm, zB Belegtmelder: Instanz-Nummer (Klassenvariable) mit im
        // String, um mehrere Fensterpositionen zu speichern
        // auch SX-adresse jeweils speichern.
        String myInst = "VT";
        prefs.putInt(myInst + "windowX", getX());
        prefs.putInt(myInst + "windowY", getY());
        prefs.putInt(myInst + "locoAdr", locoAdr);
        prefs.putInt(myInst + "sensorAdr", sensorAdr);
    }

    private void loadPrefs() {
        // reload the positions for the right instance
        String myInst = "VT";
        setLocation(prefs.getInt(myInst + "windowX", 200), prefs.getInt(myInst + "windowY", 200));
        locoAdr = prefs.getInt(myInst + "locoAdr", locoAdr);
        sensorAdr = prefs.getInt(myInst + "sensorAdr", sensorAdr);
        comboSelAddress.setSelectedIndex(sensorAdr-1);
        comboSelAddressLoco.setSelectedIndex(locoAdr-1);
        //l1.setLok_adr(prefs.getInt(myInst + "adr1", 1));
        //xbeeSerialPort = prefs.get("radioPort", "");
        //setSize(prefs.getInt("width", 500),prefs.getInt("height",300));
    }

    private void sleepSomeMillis() {
        try {
            Thread.sleep(50);
        } catch (InterruptedException ex) {
            //Logger.getLogger(LocoProgUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox comboSelAddress;
    private javax.swing.JComboBox comboSelAddressLoco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblCount;
    // End of variables declaration//GEN-END:variables

}
